<?php
// Plugin definition
$plugin = array(
  'title' => t('Oahu'),
  'icon' => 'oahu.png',
  'category' => t('Open Berkeley'),
  'theme' => 'oahu',
  'css' => 'oahu.css',
  'regions' => array(
    'header' => t('Header'),
    'column1' => t('Row 1: First Column'),
    'column2' => t('Row 1: Second Column'),
    'column3' => t('Row 1: Third Column'),
    'secondcolumn1' => t('Row 2: First Column'),
    'secondcolumn2' => t('Row 2: Second Column'),
    'secondcolumn3' => t('Row 2: Third Column'),
    'thirdcolumn1' => t('Row 3: First Column'),
    'thirdcolumn2' => t('Row 3: Second Column'),
    'thirdcolumn3' => t('Row 3: Third Column'),
    'fourthcolumn1' => t('Row 4: First Column'),
    'fourthcolumn2' => t('Row 4: Second Column'),
    'fourthcolumn3' => t('Row 4: Third Column'),
  ),
);
