<?php
/**
 * UCB Open Berkeley customizations
 */

//TODO: Revisit this as an OB Feature (or Panopoly/feature override)

/**
 * Implementation of hook_form_alter
 *
 */
function ucb_openberkeley_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case "views_form_control_users_page_1":
      if (!isset($form['add_roles']) || (!isset($form['remove_roles']))) {
        break;
      }
      $admin_rid = variable_get('user_admin_role');
      $roles = user_roles();
      $admin_rolename = NULL;
      if ((!is_array($roles)) || (!array_key_exists($admin_rid, $roles))) {
        drupal_set_message("Roles may be misconfigured. Possible security implications. Ask your administrator to check on this.", "warning");
      }
      else {
       $admin_rolename = $roles[$admin_rid];
      }

      while (list($k, $v)  = each($form['add_roles']['#options'])) {
        if ($v == $admin_rolename) {
          unset($form['add_roles']['#options'][$k]);
        }
      }
      while (list($k, $v)  = each($form['remove_roles']['#options'])) {
        if ($v == $admin_rolename) {
          unset($form['remove_roles']['#options'][$k]);
        }
      }
      break;
    case "panopoly_page_node_form":
      //Temporary Form Alter since Panopoly 1.1 adds new fields. Revisit when assessing feature.
      //Hide Feature Content checkbox and Categories label on node/add/panopoly-page
      $form['field_featured_status']['#access'] = FALSE;
      $form['field_featured_categories']['#access'] = FALSE;
      break;
  }
}
