<?php
/**
 * UCB dev/test/live config
 */

/**
 * Implementation of hook_boot().
 */
function ucb_envconf_boot() {
	$env = '';
	$site_env = '';
	//if (isset($GLOBALS['_SERVER']['PANTHEON_ENVIRONMENT'])) $env = $GLOBALS['_SERVER']['PANTHEON_ENVIRONMENT'];
	if (isset($_SERVER['PANTHEON_ENVIRONMENT'])) $env = $_SERVER['PANTHEON_ENVIRONMENT'];

	/*
	 * Check the Pantheon environment variable first, if it has a value the operators will
	 * short circuit and the preg_match()s will never be evaluated. This is good since pregs
	 * are slow.
	 *
	 * The pregs are left in here so we can adapt this to non-Pantheon servers in the future.
	 * Also so it will work with 'localhost' or 'local' urls.
	 */

	if ($env == 'live') {
		$site_env = 'live';
	}
	elseif ($env == 'test') {
		$site_env = 'test';
	}
	elseif (($env == 'dev') ||
	(preg_match('/[\w\.\-_]*\.localhost:{0,1}(?=\d{0,})/', $_SERVER['HTTP_HOST']) === 1) ||
	(preg_match('/[\w\.\-_]*\.local:{0,1}(?=\d{0,})/', $_SERVER['HTTP_HOST']) === 1)) {
		//Matched a dev domain
		$site_env = 'dev';
	}

	/*
	 * it would be nice to only inject configuration when the corresponding module is present
	 * but to minimize processing in hook_boot() we will simply inject the configuration blindly
	 * as we would if we were overriding these values in settings.php

	 $list = module_list(TRUE);
	 // Perform module-specific variable alterations
	 if (isset($list['cas'])) ucb_envconf_cas($site_env);
	 if (isset($list['cas_attributes'])) ucb_envconf_cas_attributes($site_env);

	 */
	ucb_envconf_cas($site_env);
	ucb_envconf_cas_attributes($site_env);
}


/**
 * cas settings
 */
function ucb_envconf_cas($env) {
	global $conf;
	switch($env) {
		case "dev":
		case "test":
			$conf['cas_server'] = 'auth-test.berkeley.edu';
			break;
		case "live":
			$conf['cas_server'] = 'auth.berkeley.edu';
			break;
	}
}

/**
 * cas_attributes settings
 */
function ucb_envconf_cas_attributes($env) {
	global $conf;
	switch($env) {
		case "dev":
		case "test":
			$conf['cas_attributes']['ldap']['server'] = 'ucb_test';
			break;
		case "live":
			$conf['cas_attributes']['ldap']['server'] = 'ucb_prod';
			break;
	}

}

/**
 * Implements hook_form_alter().
 *
 * Let users know that certain admin form values are "locked" by this module
 */
function ucb_envconf_form_alter(&$form, &$form_state, $form_id) {
	switch ($form_id) {
		case "cas_admin_settings":
			$form['server']['cas_server']['#disabled'] = TRUE;
			$form['server']['cas_server']['#description'] = t('<em><strong>Setting locked by ucb_envconf.module</strong></em><br />') . $form['server']['cas_server']['#description'];
			break;
		case "cas_attributes_admin_settings":
			$form['#after_build'][] = 'ucb_envconf_cas_attributes_after_build';

			break;
		case "ldap_servers_admin_form":
			$form['server']['sid']['#disabled'] = TRUE;
			$form['server']['sid']['#description'] = t('<em><strong>Setting locked by ucb_envconf.module</strong></em><br />') . $form['server']['sid']['#description'];
			break;
	}
}

function ucb_envconf_cas_attributes_after_build($form, &$form_state) {
	$form['cas_attributes']['ldap']['server']['#disabled'] = TRUE; //FIXME
	$form['cas_attributes']['ldap']['server']['#description'] = t('<em><strong>Setting locked by ucb_envconf.module</strong></em><br />') . $form['cas_attributes']['ldap']['server']['#description'];
	return $form;
}

